# 数据相关配置
data_dir: 'E:\\pycharm\\data\\s20'
k_fold: 5
batch_size: 32
threshold: 0.2
window_size: 100
step: 12
feature: 'FC'

# 模型相关配置
input_dim: 90
d_model: 256
nhead: 2
num_layers: 1
dim_feedforward: 1024

# 训练相关配置
learning_rate: 0.0001
weight_decay: 0.00005
epochs: 130

# 早停策略配置
early_stopping_patience: 200
early_stopping_min_delta: 0.05

mixup_alpha: 0.2  # 添加 Mixup 参数